import WooCommerceAPI from '@woocommerce/woocommerce-rest-api';

export const wcApi = new WooCommerceAPI({
    url: `${window.location.origin}/`,
    consumerKey: `${process.env.WC_KEY}`,
    consumerSecret: `${process.env.WC_SECRET}`,
    wpAPI: true,
    version: 'wc/v3',
    verifySsl: false, // @TODO Turn ON before set SSL on prod
    queryStringAuth: true // Something for HTTPS
});

export const Api = {
    apiUrl: `${window.location.origin}/wp-json/wp/v2/`,
    get(request) {
        return fetch(this.apiUrl + request).then(response => response.json()).then(response => response);
    }
}

export const reactLocale = {
    cookie_message_text: 'Denne hjemmeside bruger cookies til trafikmåling og optimering af indhold.',
    cookie_accept_text: 'Acceptér',
    productdetails_amountinstock: 'er på lager',
    productdetails_instock: '+50 på lager',
    productdetails_instock_regular: 'På lager',
    productdetails_instock_dynamic: '{number} på lager',
    productdetails_nostock: 'Ikke på lager',
    productdetails_shipping: 'Fragt fra 29 DKK',
    productdetails_delivery: 'Leveres indenfor 2 hverdage',
    productdetails_buy_button: 'Køb nu',
    productdetails_gift_button: 'Vælg gave',
    productdetails_gift_button_max_reached: 'Gave er allerede valgt',
    productdetails_select_prefix: '-- Vælg venligst --',
    productdetails_stock_message: 'Produktet er udsolgt - kontakt os for information',
    productdetails_stock_limited_message: 'Der er ikke flere på lager end tidligere valgte antal',
    productdetails_error_message: 'Kontroller at alle felter er valgt!',
    productdetails_variant_color: 'Farve',
    productdetails_variant_size: 'Størrelse',
    productdetails_related_title: 'Relaterede produkter',
    productdetails_about_manufacturer: 'Om',
    productdetails_go_back: 'Tilbage til oversigt',
    instantsearch_results_text: 'Se alle resultater',
    instantsearch_no_results_text: 'Ingen produkter opfylder søgekriterierne',
    instantsearch_search_text: 'Søg efter produkter',
    modal_close: 'Ok',
    modal_login_footer_text: '<strong>Spørgsmål?</strong> Ring til os på tlf. <a href=\'#\'>40 760 760</a> eller send en mail på <a href=\'#\'>kontakt@schaltzfirmagaver.dk</a>',
    modal_shopmore: 'Shop videre',
    modal_shopmore_gave: 'Gå til oversigten',
    modal_tocart: 'Gå til kurv',
    modal_add_gave_text: 'Succes - dit gavevalg er bekræftet',
    product_button_shopnow: 'Se gave',
    product_sizes_instock: 'Størrelser på lager',
    product_call_for_price: 'Ring for pris',
    product_badge_sale: 'Tilbud',
    product_badge_outofstock: 'Udsolgt',
    product_lowest_price_pre_string: 'Fra: ',
    product_button_disabled: 'Udsolgt',
    modal_giftcard_title: 'Du har oprettet et gavekort til ',
    modal_giftcard_text: 'Gavekortet vil blive sendt til følgende E-mail: ',
    modal_giftcard_info: 'Husk at afslutte din ordre i kurven!',
    offcanvas_goto: 'Gå til ',
    mailchimp_name: 'Dit navn..',
    mailchimp_email: 'Din email..',
    mailchimp_gdpr: 'Jeg accepterer, at modtage nyhedsbreve hver måned med nyheder, konkurrencer mm. ',
    mailchimp_gdpr_button: 'Læs vores persondatapolitik her',
    mailchimp_button_signup: 'Ja tak, tilmeld',
    mailchimp_error: 'Der er sket en fejl, tjek din email adresse er korrekt og at navn er udfyldt.',
    mailchimp_success: 'Tak for din tilmelding til nyhedsbrev',
    cart_subtotal: 'Sub Total:',
    cart_tax: 'Heraf moms:',
    cart_total: 'Total ordre:',
    cart_shipping: 'Forsendelse',
    cart_shipping_delivery: 'Leveringsoplysninger',
    cart_shipping_giftcard_title: 'Gavekort - afsendelse via e-mail',
    cart_shipping_toaddress: 'Levering til hjemmeadresse eller anden adresse',
    cart_shipping_droppoint_zip_missing: 'Indtast postnummer under dine informationer!',
    cart_shipping_second_adress: 'Levering til anden adresse',
    cart_shipping_second_adress_info: 'Du har valgt en fragtmetode, hvor postnummeret angiver leveringsadressen',
    cart_step_1: 'Step 1:',
    cart_step_2: 'Step 2:',
    cart_step_3: 'Step 3:',
    cart_product_overview: 'Ordreoversigt',
    cart_payment: 'Betaling',
    cart_payment_giftcard: 'Betaling med gavekort',
    cart_giftcard: 'Gavekort',
    cart_field_customertype: 'Kundetype',
    cart_field_firstname: 'Fornavn',
    cart_field_lastname: 'Efternavn',
    cart_field_email: 'E-mail',
    cart_field_phone: 'Telefonnummer',
    cart_field_adress: 'Adresse',
    cart_field_zipcode: 'Postnummer',
    cart_field_city: 'By',
    cart_field_country: 'Land',
    cart_field_company: 'Evt. firmanavn el. c/o',
    cart_field_firstname_invalid: 'Fornavn er ugyldig',
    cart_field_lastname_invalid: 'Efternavn er ugyldig',
    cart_field_email_invalid: 'E-mail er ugyldig',
    cart_field_phone_invalid: 'Telefonnummer ugyldig',
    cart_field_adress_invalid: 'Adresse er ugyldig',
    cart_field_zipcode_invalid: 'Postnummer er ugyldig',
    cart_field_city_invalid: 'By er ugyldig',
    cart_field_country_invalid: 'Land er ugyldig',
    cart_field_custom_invalid: ' er ugyldig',
    cart_feature_coupon_giftcard: 'Indsæt din Rabatkode / Gavekort her',
    cart_feature_coupon_giftcard_placeholder: 'Kode',
    cart_feature_add: 'Tilføj',
    cart_feature_comment: 'Kommentar til ordre',
    cart_feature_comment_placeholder: 'Note',
    cart_feature_newsletter: 'Tilmeld nyhedsbrev',
    cart_terms_invalid: 'Du skal acceptere handelsbetingelserne',
    cart_terms_link: '/kundeservice/handelsbetingelser',
    cart_terms: 'Jeg har læst og accepteret',
    cart_terms_button: 'handelsbetingelser',
    cart_no_products: 'Indkøbskurven er tom!',
    cart_secure_text: 'Sikker betaling via SSL-forbindelse',
    cart_button_continue: 'Se indkøbskurv',
    cart_button_gotopayment: 'Godkend ordre og betal',
    cart_button_loading: 'Vent venligst...',
    cart_button_back: 'Tilbage til forsiden',
    cart_giftcard_coupon_invalid: 'Advarsel: Kuponkoden er enten ugyldig, udløbet eller har nået sin brugsgrænse!',
    cart_coupons_invalid: 'Rabatkoder kan ikke kombineres med nedsatte produkter',
    cart_product_stock_invalid: 'Lagerbeholdning er begrænset',
    cart_product_stock_available: 'Er kun tilgængelig i mængden',
    cart_product_stock_error: 'Er ikke tilgængelige i den ønskede mængde eller er ikke på lager',
    cart_product_soldout: 'Varen er udsolgt',
    cart_product_invalid: 'Produktet er udgået - kontakt os for information',
    cart_droppoint_invalid: 'er valgt, postnummer ugyldig',
    accept_gdpr_policy: 'Accepter betingelser'
    ,
    string(string) {
        return (this[string] != undefined)
            ? this[string]
            : `${string} Not Defined`;
    }
}
